### ISSUE TITLE
'Internal Server Error'

### ISSUE THREAD

**Issue by hvrivera** [DurgNomis-drol/mytoyota#187]
Retrying setup: 500, message='Internal Server Error', url=URL('https://oneapi.telematicsct.com/v2/legacy/remote/status')

Sensors are unavailable
2022-09-08 18:11:47.686 ERROR (MainThread) [custom_components.toyota_na] Error fetching data
Traceback (most recent call last):
  File "/config/custom_components/toyota_na/__init__.py", line 104, in update_vehicles_status
    raw_vehicles = await get_vehicles(client)
  File "/usr/local/lib/python3.10/site-packages/toyota_na/vehicle/vehicle.py", line 36, in get_vehicles
    await vehicle.update()
  File "/usr/local/lib/python3.10/site-packages/toyota_na/vehicle/vehicle_generations/seventeen_cy.py", line 86, in update
    vehicle_status = await self._client.get_vehicle_status(
  File "/usr/local/lib/python3.10/site-packages/toyota_na/client.py", line 65, in get_vehicle_status
    return await self.get_vehicle_status_17cy(vin)
  File "/usr/local/lib/python3.10/site-packages/toyota_na/client.py", line 75, in get_vehicle_status_17cy
    return await self.api_get(
  File "/usr/local/lib/python3.10/site-packages/toyota_na/client.py", line 41, in api_get
    return await self.api_request("GET", endpoint, header_params)
  File "/usr/local/lib/python3.10/site-packages/toyota_na/client.py", line 31, in api_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError

**Comment by joro75** [comment]
@hvrivera The paths in the stack call log, are showing Toyota_na in the path names. Also the URL of the server seems to be strange to me.  Could it be that you are living in North America, and that you are using the toyota_na library? That is another library, and is not supported by us. If this is the case, please report this problem at: https://github.com/toyotha/Toyota-na
