### ISSUE TITLE
Authentication Failed. Unknown method.

### ISSUE THREAD

**Issue by aventi-lasith** [DurgNomis-drol/mytoyota#295]
**Describe the bug**
Authentication is not working. 

```bash
Logging in...
Traceback (most recent call last):
  File "/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/387e0f16919e6d7c21c3fbd983fea1ba949b10b954c00eef297e8363c9452535/new.py", line 85, in <module>
    loop.run_until_complete(get_information())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/mnt/wsl/docker-desktop-bind-mounts/Ubuntu/387e0f16919e6d7c21c3fbd983fea1ba949b10b954c00eef297e8363c9452535/new.py", line 45, in get_information
    await client.login()
  File "/home/lasith/.local/lib/python3.10/site-packages/mytoyota/client.py", line 58, in login
    await self._api.controller.login()
  File "/home/lasith/.local/lib/python3.10/site-packages/mytoyota/controller.py", line 62, in login
    await self._update_token()
  File "/home/lasith/.local/lib/python3.10/site-packages/mytoyota/controller.py", line 74, in _update_token
    await self._authenticate()
  File "/home/lasith/.local/lib/python3.10/site-packages/mytoyota/controller.py", line 105, in _authenticate
    raise ToyotaLoginError("Authentication Failed. Unknown method.")
mytoyota.exceptions.ToyotaLoginError: Authentication Failed. Unknown method.
```

**To Reproduce**
`python simple_client_example.py`

**Comment by CM000n** [comment]
Hello @aventi-lasith , can you please give us some additional information? 
Which vehicle or vehicles do you own? Are these vehicles already registered with Toyota Connected Services?
Are you still using the old [MyT](https://play.google.com/store/apps/details?id=app.mytoyota.toyota.com.mytoyota&hl=de&gl=DE) app, or are you already using the current [MyToyota](https://play.google.com/store/search?q=MyToyota&c=apps&hl=de&gl=DE) app?

**Comment by aventi-lasith** [comment]
Hi,
Of course. I have 3 vehicles in my account but one is inactive. And yes I'm already using the MyT app. The connected services are activated for all vehicles. I've been using mytoyota v0.9 until December. 

But this issue happens when logging in before any vehicle data were pulled. 

Logging in with v0.9 still works if I'm not mistaken.

**Comment by CM000n** [comment]
Version >= 1.0 is not compatible with vehicles that are still registered under the old MyT app. See also current README.md File in this repo.
Please register your vehicle under the current MyToyota app first to be able to use the new API.

**Comment by aventi-lasith** [comment]
Ok. Thanks. Unfortunately, for some reason it doesn't allow me to add the vehicles to the new MyToyota app

**Comment by CM000n** [comment]
> Ok. Thanks. Unfortunately, for some reason it doesn't allow me to add the vehicles to the new MyToyota app

Okay, we can't do anything about that. That's a case for official Toyota support 😉

**Comment by aventi-lasith** [comment]
Yes, I'll contact Toyota support.

The problem is that the version 0.9 is not working anymore either. 

`/vehicles` endpoint works. But `/vehicle/vin/addtionalInfo` endpoint fails with a 403 (Action is not supported on this vehicle).

Is this expected?
