### ISSUE TITLE
AttributeError: 'MyT' object has no attribute 'get_vehicle_status'

### ISSUE THREAD

**Issue by urko1982** [DurgNomis-drol/mytoyota#41]
I obtain without problems the list of  my cars registered in my Toyota account using _await client.get_vehicles()_ However when I try to access more specific information about any vehicle using  _await client.get_vehicle_status(car)_ rises an error _AttributeError: 'MyT' object has no attribute 'get_vehicle_status'_

In local machine there is no problem,

```
Requirement already satisfied: mytoyota in ./.local/lib/python3.7/site-packages (0.2.2)
Requirement already satisfied: langcodes in ./.local/lib/python3.7/site-packages (from mytoyota) (3.1.0)
Requirement already satisfied: pendulum in ./.local/lib/python3.7/site-packages (from mytoyota) (2.1.2)
Requirement already satisfied: httpx in ./.local/lib/python3.7/site-packages (from mytoyota) (0.19.0)
Requirement already satisfied: httpcore<0.14.0,>=0.13.3 in ./.local/lib/python3.7/site-packages (from httpx->mytoyota) (0.13.6)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in ./.local/lib/python3.7/site-packages (from httpx->mytoyota) (1.5.0)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpx->mytoyota) (2018.8.24)
Requirement already satisfied: sniffio in ./.local/lib/python3.7/site-packages (from httpx->mytoyota) (1.2.0)
Requirement already satisfied: charset-normalizer in ./.local/lib/python3.7/site-packages (from httpx->mytoyota) (2.0.4)
Requirement already satisfied: anyio==3.* in ./.local/lib/python3.7/site-packages (from httpcore<0.14.0,>=0.13.3->httpx->mytoyota) (3.3.0)
Requirement already satisfied: h11<0.13,>=0.11 in ./.local/lib/python3.7/site-packages (from httpcore<0.14.0,>=0.13.3->httpx->mytoyota) (0.12.0)
Requirement already satisfied: idna>=2.8 in ./.local/lib/python3.7/site-packages (from anyio==3.*->httpcore<0.14.0,>=0.13.3->httpx->mytoyota) (3.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from anyio==3.*->httpcore<0.14.0,>=0.13.3->httpx->mytoyota) (3.10.0.0)
Requirement already satisfied: pytzdata>=2020.1 in ./.local/lib/python3.7/site-packages (from pendulum->mytoyota) (2020.1)
Requirement already satisfied: python-dateutil<3.0,>=2.6 in /usr/lib/python3/dist-packages (from pendulum->mytoyota) (2.7.3)
```

```
Django Version: 3.2.6
Python Version: 3.7.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/api/geo/views.py", line 19, in get_toyota
    return HttpResponse(toyota.main())
  File "/opt/api/geo/auxiliar/toyota.py", line 45, in main
    loop.run_until_complete(get_information())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/opt/api/geo/auxiliar/toyota.py", line 36, in get_information
    vehicle = await client.get_vehicle_status(car)

Exception Type: AttributeError at /geo/get_toyota
Exception Value: 'MyT' object has no attribute 'get_vehicle_status'
```

**Comment by DurgNomis-drol** [comment]
You have to update the mytoyota package to the latest one (0.5.1) 😊 You are running 0.2.2. There are not any pre build wheels for 3.7, so you would have to update you 3.8 or above. 

But as you are not the only one that are trying to use 3.7, I will look into adding support for 3.6 and 3.7 😊

**Comment by DurgNomis-drol** [comment]
@urko1982 This should be fixed now, the newest release supports python 3.7, please update through pip.
